# server port settig
server:
  port: 8007
# db setting
spring:
  application:
    name: memo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres  
    password: 123456 
    driverClassName: org.postgresql.Driver
  
# print SQL statement.
logging: 
  level:
    org.springframework:
      jdbc:
        core: TRACE